name: web
replicas: 1
containers:
- image: wordpress:4
  env:
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
  - name: WORDPRESS_DB_USER
    value: wordpress
services:
- name: wordpress
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
configData:
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_HOST: "database:3306"
